#!/usr/bin/env bash
# Prints the whole text of the Obsidian vault,
# with filenames preceding each file content,
# suitable for ingestion by LLM
cd "$(dirname "$0")"
./whole-text | ./copy-to-clipboard